import type { Item } from '../../engine/types'
import { stitchSvg } from './stitch'

/**
 * Badge motifs as cross-stitch grids (colour key in stitch.ts).
 */
const motifs: Record<string, string[]> = {
  flower: [
    '..rr.rr..',
    '.rrrrrrr.',
    '.rrrwrrr.',
    '..rrrrr..',
    '..rr.rr..',
    '....g....',
    '.pp.g.pp.',
    '..ppgpp..',
    '....g....',
  ],
  infinity: [
    '.pppp...pppp.',
    'pp..pp.pp..pp',
    'p....ppp....p',
    'p....ppp....p',
    'pp..pp.pp..pp',
    '.pppp...pppp.',
  ],
  hourglass: [
    'ggggggggg',
    '.g.....g.',
    '.grrrrrg.',
    '..grrrg..',
    '...grg...',
    '....g....',
    '...g.g...',
    '..g.r.g..',
    '.g.rrr.g.',
    '.grrrrrg.',
    'ggggggggg',
  ],
  star: [
    '....b....',
    '....b....',
    '...bbb...',
    'bbbbbbbbb',
    '.bbbbbbb.',
    '..bbbbb..',
    '..bb.bb..',
    '.bb...bb.',
    '.b.....b.',
  ],
  heart: [
    '.rr...rr.',
    'rrrr.rrrr',
    'rrwrrrrrr',
    'rrrrrrrrr',
    '.rrrrrrr.',
    '..rrrrr..',
    '...rrr...',
    '....r....',
  ],
  cherries: [
    '......gg.',
    '.....g.g.',
    '....g..g.',
    '...g...g.',
    '..g....g.',
    '.rrr..rrr',
    'rwrrrrwrr',
    'rrrrrrrrr',
    '.rrr..rrr',
  ],
  // ---- Item badges, batch 1 ----
  'snail-crown': [
    '........y.y',
    '........yyy',
    '..ppp...s.s',
    '.p...p..s.s',
    'p..gg.p.sss',
    'p.g..gp.ss.',
    'p..gg.pss..',
    '.p...pss...',
    'sssssssss..',
  ],
  'snail': [
    '..ppp...s.s',
    '.p...p..s.s',
    'p..gg.p.sss',
    'p.g..gp.ss.',
    'p..gg.pss..',
    '.p...pss...',
    'sssssssss..',
  ],
  'sinking-ship': [
    '..g........',
    '..gw.......',
    '..gww......',
    '..gwww.....',
    'rrrrrrr....',
    '.rrrrrrr...',
    'bbbbbrrrbbb',
    '.b.b.b.b.b.',
  ],
  'fish-bicycle': [
    '...ttt.....',
    '.tttttt.t..',
    'ttgtttttt..',
    '.tttttt.t..',
    '...ttt.....',
    '....g.g....',
    '.g..ggg..g.',
    'g.g.g.g.g.g',
    '.g.......g.',
  ],
  'eye-spoon': [
    '..eeeee..',
    '.e.....e.',
    'e..ggg..e',
    'e.gbbbg.e',
    'e..ggg..e',
    '.e.....e.',
    '..eeeee..',
    '....e....',
    '....e....',
    '....e....',
  ],
  'anchor': [
    '....bbb....',
    '....b.b....',
    '....bbb....',
    '..bbbbbbb..',
    '.....b.....',
    '.....b.....',
    '.....b.....',
    'b....b....b',
    '.b...b...b.',
    '..bbbbbbb..',
  ],
  'sleepy-moon': [
    '........bbb',
    '...yyy...b.',
    '.yyy....bbb',
    'yyy........',
    'yy.g.g.....',
    'yy..g......',
    'yyy........',
    '.yyy......y',
    '..yyyyyyyy.',
    '....yyyy...',
  ],
  'crown': [
    'y...y...y',
    'yy.yyy.yy',
    'yyyyyyyyy',
    'yryyyyyry',
    'yyyyyyyyy',
  ],
  'teapot': [
    '.....g.....',
    '...ttttt...',
    'g.ttttttt.t',
    'g.tttwtttt.',
    'g.ttttttt..',
    '.gttttttt..',
    '...ttttt...',
  ],
  'joystick': [
    '....rrr....',
    '...rrrrr...',
    '....rrr....',
    '.....g.....',
    '.....g.....',
    '.ggggggggg.',
    '.gpppppppg.',
    '.ggggggggg.',
  ],
  'heart-eyes': [
    '...yyyyy...',
    '.yyyyyyyyy.',
    'yr.ryyyr.ry',
    'yrrryyyrrry',
    'yyryyyyyryy',
    'yyyyyyyyyyy',
    'yygyyyyygyy',
    '.yygggggyy.',
    '...yyyyy...',
  ],
  'rain-cloud': [
    '...eee.....',
    '.eeeeeee...',
    'eeeeeeeeee.',
    '.eeeeeeee..',
    '...........',
    '.b..b..b...',
    'b..b..b....',
  ],
  'four-leaf': [
    '.nn...nn.',
    'nnnn.nnnn',
    'nnnnnnnnn',
    '.nnnnnnn.',
    '..nnwnn..',
    '.nnnnnnn.',
    'nnnnnnnnn',
    'nnnn.nnnn',
    '.nn.g.nn.',
    '....g....',
    '...g.....',
  ],
  'horseshoe': [
    '.eeeeeee.',
    'ee.....ee',
    'e.......e',
    'ew.....we',
    'e.......e',
    'ew.....we',
    'e.......e',
    'ee.....ee',
  ],
  'duck-moustache': [
    '...yyyy....',
    '..yyyyyy...',
    '..yygyyy...',
    '..yyyyyrrr.',
    '..yyggg....',
    '.yyyyyyy...',
    'yyyyyyyyyy.',
    'yyyyyyyyy..',
    '.yyyyyyy...',
  ],
  'ghost-briefcase': [
    '..eeeee....',
    '.eeeeeee...',
    '.egeegee...',
    '.eeeeeee...',
    '.eeegeee...',
    '.eeeeeee...',
    '.eeeeeeegg.',
    '.e.e.e.gggg',
    '.......gggg',
  ],
  'tangled-thread': [
    '..rrr......',
    '.r...r.pp..',
    'r..pp.rp..p',
    'r.p..rpr..p',
    '.r.p.r.p.p.',
    '..rpr..pp..',
    '.p.r.r.....',
    'p...rr.....',
    '...r..r....',
  ],
  'tin-pearls': [
    '.eeeeeee.',
    'eeeeeeeee',
    'wweeeeeww',
    'ewweeewwe',
    'eewwwwwee',
    'eeeeeeeee',
    'eeeeeeeee',
    '.eeeeeee.',
  ],
  'platform-shoe': [
    'rr.........',
    'rrr........',
    'rrrrr......',
    'rrrrrrrrr..',
    'rrrrrrrrrrr',
    'yyyyyyyyyyy',
    'yyyyyyyyyyy',
    'yyyyyyyyyyy',
  ],
  'one-size-sock': [
    '...bbbb.',
    '...wwww.',
    '...bbbb.',
    '...bbbb.',
    '...bbbb.',
    '..bbbbb.',
    'bbbbbbb.',
    'bbbbbb..',
    '.bbb....',
  ],
  'owl': [
    'p.......p',
    'ppppppppp',
    'pwwpppwwp',
    'pwgpppgwp',
    'pwwpypwwp',
    '.ppppppp.',
    '.pwpwpwp.',
    '.ppppppp.',
    '..y...y..',
  ],
  'camera': [
    '..ggg......',
    'ggggggggggg',
    'g...ggg...g',
    'g..gbbbg..g',
    'g..gbwbg..g',
    'g..gbbbg..g',
    'g...ggg...g',
    'ggggggggggg',
  ],
  'envelope': [
    'rrrrrrrrrrr',
    'rr.......rr',
    'r.r.....r.r',
    'r..r...r..r',
    'r...rrr...r',
    'r.........r',
    'rrrrrrrrrrr',
  ],
  'trophy': [
    '.yyyyyyy.',
    'yyyyyyyyy',
    'y.yyyyy.y',
    '.yyyyyyy.',
    '..yyyyy..',
    '...yyy...',
    '....y....',
    '...ppp...',
    '..ppppp..',
  ],
  'rocket': [
    '.....r.....',
    '....rrr....',
    '....eee....',
    '....ebe....',
    '....eee....',
    '...reeer...',
    '..rr.e.rr..',
    '.....y.....',
    '....y.y....',
  ],
  'crab': [
    'r.......r',
    'rr.....rr',
    '.r.g.g.r.',
    '..rrrrr..',
    'rrrrrrrrr',
    '..rrrrr..',
    '.r.r.r.r.',
  ],
  'tiny-storm': [
    '.ggg...',
    'ggggggg',
    '.ggggg.',
    '...y...',
    '..y....',
    '...y...',
  ],
  'dice': [
    'ggggggg',
    'gr...rg',
    'g.....g',
    'g..r..g',
    'g.....g',
    'gr...rg',
    'ggggggg',
  ],
  lock: [
    '.###.',
    '#...#',
    '#...#',
    '#####',
    '##.##',
    '##.##',
    '#####',
  ],
  plus: ['.#.', '###', '.#.'], // current colour
  sparkle: [
    '....t....',
    '....t....',
    '...ttt...',
    'tttt.tttt',
    '...ttt...',
    '....t....',
    '....t....',
  ],
}

/** Until every item has its own motif, families borrow a shared one. */
const familyMotif: Record<string, string> = {
  Ambient: 'star', Collection: 'heart', Commerce: 'cherries', Community: 'heart', 'Creative studio': 'star',
  Game: 'cherries', Learning: 'star', 'Live experience': 'sparkle', 'Map & explorer': 'star',
  'Personal space': 'flower', Publication: 'heart', 'Self-discovery': 'sparkle', Simulator: 'infinity',
  Story: 'heart', Tool: 'hourglass', Toy: 'cherries',
  Abstract: 'infinity', 'Digital life': 'infinity', 'Everyday life': 'flower', Ritual: 'hourglass',
  Social: 'heart', State: 'sparkle', 'Time & attention': 'hourglass',
  Behaviour: 'heart', Mechanism: 'infinity', 'Technical constraint': 'hourglass', 'Visual reference': 'star',
}

export const isDrawn = (name: string) => name in motifs

export function motifFor(item: Item): string {
  return motifs[item.badge] ? item.badge : familyMotif[item.family] ?? 'sparkle'
}

export function motifSvg(name: string): string {
  return stitchSvg(motifs[name] ?? motifs.sparkle)
}

export const badgeSvg = (item: Item) => motifSvg(motifFor(item))
