import type { Item } from '../../engine/types'
import { stitchSvg } from './stitch'
import motifText from './motifs.txt?raw'

/**
 * Badge motifs as cross-stitch grids (colour key in stitch.ts).
 */
const motifs: Record<string, string[]> = {
  flower: [
    '..rr.rr..',
    '.rrrrrrr.',
    '.rrrwrrr.',
    '..rrrrr..',
    '..rr.rr..',
    '....g....',
    '.pp.g.pp.',
    '..ppgpp..',
    '....g....',
  ],
  infinity: [
    '.pppp...pppp.',
    'pp..pp.pp..pp',
    'p....ppp....p',
    'p....ppp....p',
    'pp..pp.pp..pp',
    '.pppp...pppp.',
  ],
  hourglass: [
    'ggggggggg',
    '.g.....g.',
    '.grrrrrg.',
    '..grrrg..',
    '...grg...',
    '....g....',
    '...g.g...',
    '..g.r.g..',
    '.g.rrr.g.',
    '.grrrrrg.',
    'ggggggggg',
  ],
  star: [
    '....b....',
    '....b....',
    '...bbb...',
    'bbbbbbbbb',
    '.bbbbbbb.',
    '..bbbbb..',
    '..bb.bb..',
    '.bb...bb.',
    '.b.....b.',
  ],
  heart: [
    '.rr...rr.',
    'rrrr.rrrr',
    'rrwrrrrrr',
    'rrrrrrrrr',
    '.rrrrrrr.',
    '..rrrrr..',
    '...rrr...',
    '....r....',
  ],
  cherries: [
    '......gg.',
    '.....g.g.',
    '....g..g.',
    '...g...g.',
    '..g....g.',
    '.rrr..rrr',
    'rwrrrrwrr',
    'rrrrrrrrr',
    '.rrr..rrr',
  ],
  // ---- Item badges, batch 1 ----
  'snail-crown': [
    '........y.y',
    '........yyy',
    '..ppp...s.s',
    '.p...p..s.s',
    'p..gg.p.sss',
    'p.g..gp.ss.',
    'p..gg.pss..',
    '.p...pss...',
    'sssssssss..',
  ],
  'snail': [
    '..ppp...s.s',
    '.p...p..s.s',
    'p..gg.p.sss',
    'p.g..gp.ss.',
    'p..gg.pss..',
    '.p...pss...',
    'sssssssss..',
  ],
  'sinking-ship': [
    '..g........',
    '..gw.......',
    '..gww......',
    '..gwww.....',
    'rrrrrrr....',
    '.rrrrrrr...',
    'bbbbbrrrbbb',
    '.b.b.b.b.b.',
  ],
  'anchor': [
    '....bbb....',
    '....b.b....',
    '....bbb....',
    '..bbbbbbb..',
    '.....b.....',
    '.....b.....',
    '.....b.....',
    'b....b....b',
    '.b...b...b.',
    '..bbbbbbb..',
  ],
  'sleepy-moon': [
    '........bbb',
    '...yyy...b.',
    '.yyy....bbb',
    'yyy........',
    'yy.g.g.....',
    'yy..g......',
    'yyy........',
    '.yyy......y',
    '..yyyyyyyy.',
    '....yyyy...',
  ],
  'crown': [
    'y...y...y',
    'yy.yyy.yy',
    'yyyyyyyyy',
    'yryyyyyry',
    'yyyyyyyyy',
  ],
  'teapot': [
    '.....g.....',
    '...ttttt...',
    'g.ttttttt.t',
    'g.tttwtttt.',
    'g.ttttttt..',
    '.gttttttt..',
    '...ttttt...',
  ],
  'joystick': [
    '....rrr....',
    '...rrrrr...',
    '....rrr....',
    '.....g.....',
    '.....g.....',
    '.ggggggggg.',
    '.gpppppppg.',
    '.ggggggggg.',
  ],
  'heart-eyes': [
    '...yyyyy...',
    '.yyyyyyyyy.',
    'yr.ryyyr.ry',
    'yrrryyyrrry',
    'yyryyyyyryy',
    'yyyyyyyyyyy',
    'yygyyyyygyy',
    '.yygggggyy.',
    '...yyyyy...',
  ],
  'four-leaf': [
    '.nn...nn.',
    'nnnn.nnnn',
    'nnnnnnnnn',
    '.nnnnnnn.',
    '..nnwnn..',
    '.nnnnnnn.',
    'nnnnnnnnn',
    'nnnn.nnnn',
    '.nn.g.nn.',
    '....g....',
    '...g.....',
  ],
  'duck-moustache': [
    '...yyyy....',
    '..yyyyyy...',
    '..yygyyy...',
    '..yyyyyrrr.',
    '..yyggg....',
    '.yyyyyyy...',
    'yyyyyyyyyy.',
    'yyyyyyyyy..',
    '.yyyyyyy...',
  ],
  'ghost-briefcase': [
    '..eeeee....',
    '.eeeeeee...',
    '.egeegee...',
    '.eeeeeee...',
    '.eeegeee...',
    '.eeeeeee...',
    '.eeeeeeegg.',
    '.e.e.e.gggg',
    '.......gggg',
  ],
  'tangled-thread': [
    '..rrr......',
    '.r...r.pp..',
    'r..pp.rp..p',
    'r.p..rpr..p',
    '.r.p.r.p.p.',
    '..rpr..pp..',
    '.p.r.r.....',
    'p...rr.....',
    '...r..r....',
  ],
  'tin-pearls': [
    '.eeeeeee.',
    'eeeeeeeee',
    'wweeeeeww',
    'ewweeewwe',
    'eewwwwwee',
    'eeeeeeeee',
    'eeeeeeeee',
    '.eeeeeee.',
  ],
  'platform-shoe': [
    'rr.........',
    'rrr........',
    'rrrrr......',
    'rrrrrrrrr..',
    'rrrrrrrrrrr',
    'yyyyyyyyyyy',
    'yyyyyyyyyyy',
    'yyyyyyyyyyy',
  ],
  'one-size-sock': [
    '...bbbb.',
    '...wwww.',
    '...bbbb.',
    '...bbbb.',
    '...bbbb.',
    '..bbbbb.',
    'bbbbbbb.',
    'bbbbbb..',
    '.bbb....',
  ],
  'owl': [
    'p.......p',
    'ppppppppp',
    'pwwpppwwp',
    'pwgpppgwp',
    'pwwpypwwp',
    '.ppppppp.',
    '.pwpwpwp.',
    '.ppppppp.',
    '..y...y..',
  ],
  'camera': [
    '..ggg......',
    'ggggggggggg',
    'g...ggg...g',
    'g..gbbbg..g',
    'g..gbwbg..g',
    'g..gbbbg..g',
    'g...ggg...g',
    'ggggggggggg',
  ],
  'envelope': [
    'rrrrrrrrrrr',
    'rr.......rr',
    'r.r.....r.r',
    'r..r...r..r',
    'r...rrr...r',
    'r.........r',
    'rrrrrrrrrrr',
  ],
  'trophy': [
    '.yyyyyyy.',
    'yyyyyyyyy',
    'y.yyyyy.y',
    '.yyyyyyy.',
    '..yyyyy..',
    '...yyy...',
    '....y....',
    '...ppp...',
    '..ppppp..',
  ],
  'rocket': [
    '.....r.....',
    '....rrr....',
    '....eee....',
    '....ebe....',
    '....eee....',
    '...reeer...',
    '..rr.e.rr..',
    '.....y.....',
    '....y.y....',
  ],
  'crab': [
    'r.......r',
    'rr.....rr',
    '.r.g.g.r.',
    '..rrrrr..',
    'rrrrrrrrr',
    '..rrrrr..',
    '.r.r.r.r.',
  ],
  'tiny-storm': [
    '.ggg...',
    'ggggggg',
    '.ggggg.',
    '...y...',
    '..y....',
    '...y...',
  ],
  // ---- Item badges, batch 2 (15-stitch box) ----
  'horseshoe': [
    '...yyyyyyyyy...',
    '..yyyyyyyyyyy..',
    '.yyyy.....yyyy.',
    '.yyg.......gyy.',
    'yyy.........yyy',
    'yyg.........gyy',
    'yyy.........yyy',
    'yyg.........gyy',
    'yyy.........yyy',
    'yyyy.......yyyy',
    'yyyy.......yyyy',
  ],
  'rain-cloud': [
    '.....ggg.......',
    '....gwwwg.ggg..',
    '..ggwwwwwgwwwg.',
    '.gwwwwwwwwwwwg.',
    'gwwwwwwwwwwwwwg',
    'gwwwwwwwwwwwwwg',
    '.ggggggggggggg.',
    '...............',
    '..b...b...b....',
    '.b...b...b...b.',
    'b...b...b...b..',
  ],
  'fish-bicycle': [
    '......ttttt....',
    '..t.ttttttttt..',
    '..tttttttgttt..',
    '..t.ttttttttt..',
    '......ttttt....',
    '......ggg...gg.',
    '.......g.....g.',
    '.......gggggg..',
    '......g.g...g..',
    '.ggg.g...g.ggg.',
    'g...g.....g...g',
    'g.gg.gg.gg.gg.g',
    'g...g.....g...g',
    '.ggg.......ggg.',
  ],
  'dice': [
    'ggggggg........',
    'gr...rg........',
    'g.....g........',
    'g..r..g.ggggggg',
    'g.....g.gr....g',
    'gr...rg.g.....g',
    'ggggggg.g.....g',
    '........g.....g',
    '........g....rg',
    '........ggggggg',
  ],
  'eye-spoon': [
    '...eeeeeee.',
    '..eeeeeeeee',
    '.eeewwwwweee',
    '.eewwbbbwwee',
    '.eewbbgbbwee',
    '.eewwbbbwwee',
    '.eeewwwwweee',
    '..eeeeeeeee.',
    '...eeeeeee..',
    '......ee....',
    '......ee....',
    '......ee....',
    '......ee....',
    '......ee....',
  ],
  'hamster-wheel': [
    '....ggggggg....',
    '..gg.......gg..',
    '.g...........g.',
    '.g...........g.',
    'g.....sss.....g',
    'g....sssss....g',
    'g....sgsss.s..g',
    'g.....ssss....g',
    'g.............g',
    '.g...........g.',
    '.g...........g.',
    '..gg.......gg..',
    '....ggggggg....',
    '......g.g......',
    '.....g...g.....',
  ],
  'rubber-chicken': [
    '....rr.........',
    '...yyyy........',
    '...yygyrrr.....',
    '...yyyy........',
    '....yy.........',
    '....yy.........',
    '....yy.........',
    '....yyy........',
    '...yyyyyyyyy...',
    '..yyyyyyyyyyy..',
    '..yyyyyyyyyyy..',
    '...yyyyyyyyy...',
    '....r.....r....',
    '...rr....rr....',
  ],
  'sloth': [
    'nnnnnnnnnnnnnnn',
    '.g..........g..',
    '.e..........e..',
    '.ee........ee..',
    '..eeeeeeeeee...',
    '..eewwwwwwee...',
    '..ewgwwwwgwe...',
    '..ewwwwwwwwe...',
    '..eewwgggwee...',
    '...eewwwwee....',
    '....eeeeee.....',
  ],
  'melting-face': [
    '...yyyyyyy...',
    '..yyyyyyyyy..',
    '.yyyyyyyyyyy.',
    '.yyygyyygyyy.',
    '.yyyyyyyyyyy.',
    '.yyyyyyyyyyy.',
    '.yygyyyyygyy.',
    '.yyygggggyyy.',
    '.yyyyyyyyyyy.',
    '..yyy.yyy.yy.',
    '..yy..yy...y.',
    '...y...y.....',
    'yyyyyyyyyyyyy',
  ],
  'puppy': [
    '.ee.yyyyy.ee.',
    'eeeyyyyyyyeee',
    'eeeygyyygyeee',
    'eeeyyyyyyyeee',
    '.e.yyygyyy.e.',
    '...yygggyy...',
    '...yyyryyy...',
    '....yyryy....',
    '......r......',
  ],
  'elephant': [
    '....eeeeee.....',
    '..eeeeeeeeee...',
    '.eeeeeeeeeeee..',
    'eeeeeeeeeegee..',
    'eeeeeeeeeeeeee.',
    'eeeeeeeeeeeeeee',
    'eeeeeeeeeee..ee',
    '.eeeeeeeeee...e',
    '.ee.ee.ee.ee..r',
    '.ee.ee.ee.ee...',
  ],
  'paperclip-eyes': [
    '..wg...wg..',
    '..ww...ww..',
    '...eeeee...',
    '..e.....e..',
    '..e.eee.e..',
    '..e.e.e.e..',
    '..e.e.e.e..',
    '..e.e.e.e..',
    '..e.e...e..',
    '..e.eeeee..',
    '..e........',
    '...eeeeeee.',
  ],
  'space-invader': [
    '..n.....n..',
    '...n...n...',
    '..nnnnnnn..',
    '.nn.nnn.nn.',
    'nnnnnnnnnnn',
    'n.nnnnnnn.n',
    'n.n.....n.n',
    '...nn.nn...',
  ],
  'lost-cat': [
    'g.......g....',
    'gg.....gg....',
    'ggggggggg....',
    'gyggggygg....',
    'ggggsgggg....',
    '.ggggggg.....',
    '..ggggg......',
    '.ggggggg...g.',
    'ggggggggg..g.',
    'ggggggggg.g..',
    'ggggggggggg..',
  ],
  'halo': [
    '...yyyyyyy...',
    '.yy.......yy.',
    'y...........y',
    '.yy.......yy.',
    '...yyyyyyy...',
  ],
  'allen-key': [
    '..ee.........',
    '..ee.........',
    '..ee.........',
    '..ee.........',
    '..ee.........',
    '..ee.........',
    '..eeeeeeeeee.',
    '..eeeeeeeeee.',
  ],
  'dropped-ice-cream': [
    '.....y.......',
    '....yyy......',
    '....yyy......',
    '...yyyyy.....',
    '...yyyyy.....',
    '..sssssss....',
    '.sssssssss...',
    'sssssssssssss',
    '.s..s..s..s..',
  ],
  'flip-phone': [
    '.........g.',
    '..eeeeeeeg.',
    '..ebbbbbe..',
    '..ebbbbbe..',
    '..ebbbbbe..',
    '..eeeeeee..',
    '...........',
    '..eeeeeee..',
    '..egegege..',
    '..eeeeeee..',
    '..egegege..',
    '..eeeeeee..',
    '..egegege..',
    '..eeeeeee..',
  ],
  'crystal-ball': [
    '....ppppp....',
    '..ppppppppp..',
    '.ppwpppppppp.',
    '.pwppppppppp.',
    'ppppppptpppp.',
    'pppppptttpppp',
    'ppppppptppppp',
    '.ppppppppppp.',
    '..ppppppppp..',
    '....ppppp....',
    '...yyyyyyy...',
    '..yyyyyyyyy..',
  ],
  'umbrella': [
    '......g......',
    '...rrrrrrr...',
    '.rrrrrrrrrrr.',
    'rrrrrrrrrrrrr',
    'r..r..g..r..r',
    '......g......',
    '......g......',
    '......g......',
    '......g..g...',
    '.......gg....',
  ],
  'butterfly': [
    '....g...g....',
    '.....g.g.....',
    '.pp...g...pp.',
    'pppp..g..pppp',
    'ppspp.g.ppspp',
    'ppppp.g.ppppp',
    '.pppp.g.pppp.',
    '..ppp.g.ppp..',
    '.pppp.g.pppp.',
    'ppspp.g.ppspp',
    '.ppp..g..ppp.',
  ],
  'smiley': [
    '...yyyyyyy...',
    '.yyyyyyyyyyy.',
    'yyyyyyyyyyyyy',
    'yyygyyyyygyyy',
    'yyygyyyyygyyy',
    'yyyyyyyyyyyyy',
    'yygyyyyyyygyy',
    'yyygggggggyyy',
    '.yyyyyyyyyyy.',
    '...yyyyyyy...',
  ],
  'keyhole': [
    '.yyyyyyyyy.',
    'yyyyyyyyyyy',
    'yyyygggyyyy',
    'yyygggggyyy',
    'yyygggggyyy',
    'yyyygggyyyy',
    'yyyygggyyyy',
    'yyygggggyyy',
    'yyyyyyyyyyy',
    '.yyyyyyyyy.',
  ],
  'double-tick': [
    '......b.....b',
    '......bb...bb',
    '.....bb...bb.',
    'b...bb...bb..',
    'bb.bb...bb...',
    '.bbb..bbb....',
    '..b....b.....',
  ],
  'cassette': [
    'rrrrrrrrrrrrr',
    'rwwwwwwwwwwwr',
    'rwgg.....ggwr',
    'rwgg.....ggwr',
    'rwwwwwwwwwwwr',
    'rrrrrrrrrrrrr',
    'rr.rrrrrrr.rr',
    'rrrrrrrrrrrrr',
  ],
  'mondrian': [
    'ggggggggggggg',
    'grrrrrg.....g',
    'grrrrrg.....g',
    'grrrrrggggggg',
    'ggggggg...g.g',
    'g.....g...gyg',
    'g.....g...ggg',
    'gbbbbbg.....g',
    'gbbbbbg.....g',
    'ggggggggggggg',
  ],
  'window-flag': [
    'rrrrr.nnnnn',
    'rrrrr.nnnnn',
    'rrrrr.nnnnn',
    'rrrrr.nnnnn',
    '...........',
    'bbbbb.yyyyy',
    'bbbbb.yyyyy',
    'bbbbb.yyyyy',
    'bbbbb.yyyyy',
  ],
  'bauhaus-shapes': [
    '..rrr.........',
    '.rrrrr........',
    'rrrrrrr.bbbbb.',
    'rrrrrrr.bbbbb.',
    '.rrrrr..bbbbb.',
    '..rrr...bbbbb.',
    '..............',
    '......y.......',
    '.....yyy......',
    '....yyyyy.....',
    '...yyyyyyy....',
  ],
  'snow-globe': [
    '....bbbbb....',
    '..bbw...wbb..',
    '.bw..rrr..wb.',
    '.b..rrrrr..b.',
    'b..w.rgr.w..b',
    'b....rgr....b',
    '.b.........b.',
    '..bbbbbbbbb..',
    '..yyyyyyyyy..',
    '.yyyyyyyyyyy.',
  ],
  lock: [
    '.###.',
    '#...#',
    '#...#',
    '#####',
    '##.##',
    '##.##',
    '#####',
  ],
  plus: ['.#.', '###', '.#.'], // current colour
  sparkle: [
    '....t....',
    '....t....',
    '...ttt...',
    'tttt.tttt',
    '...ttt...',
    '....t....',
    '....t....',
  ],
}

/** Parses motifs.txt: blocks of `name` then stitch rows, separated by blank lines. */
function parseMotifs(text: string): Record<string, string[]> {
  const out: Record<string, string[]> = {}
  for (const block of text.split(/\n\s*\n/)) {
    const lines = block.split('\n').map((l) => l.trim()).filter((l) => l && !l.startsWith('#'))
    if (lines.length > 1) out[lines[0]] = lines.slice(1)
  }
  return out
}
Object.assign(motifs, parseMotifs(motifText))

/** Until every item has its own motif, families borrow a shared one. */
const familyMotif: Record<string, string> = {
  Ambient: 'star', Collection: 'heart', Commerce: 'cherries', Community: 'heart', 'Creative studio': 'star',
  Game: 'cherries', Learning: 'star', 'Live experience': 'sparkle', 'Map & explorer': 'star',
  'Personal space': 'flower', Publication: 'heart', 'Self-discovery': 'sparkle', Simulator: 'infinity',
  Story: 'heart', Tool: 'hourglass', Toy: 'cherries',
  Abstract: 'infinity', 'Digital life': 'infinity', 'Everyday life': 'flower', Ritual: 'hourglass',
  Social: 'heart', State: 'sparkle', 'Time & attention': 'hourglass',
  Behaviour: 'heart', Mechanism: 'infinity', 'Technical constraint': 'hourglass', 'Visual reference': 'star',
}

export const isDrawn = (name: string) => name in motifs

export function motifFor(item: Item): string {
  return motifs[item.badge] ? item.badge : familyMotif[item.family] ?? 'sparkle'
}

export function motifSvg(name: string): string {
  return stitchSvg(motifs[name] ?? motifs.sparkle)
}

/** Badges sit in a fixed 15×15 stitch box so every badge takes the same space. */
export const BADGE_BOX = 15

export const badgeSvg = (item: Item) => stitchSvg(motifs[motifFor(item)] ?? motifs.sparkle, 'badge-art', BADGE_BOX)
